// This file generated by "generate.ts lepus-ffi" in the root of the repo.
import type {
  LEPUSRuntimePointer,
  LEPUSContextPointer,
  LEPUSValuePointer,
  LEPUSValueConstPointer
} from "./lepus-types";

export type LEPUSModuleDefPointer = number;
export type JSVoidPointer = number;
export type UInt32Pointer = number;

export interface LEPUSEmscriptenModule {
  cwrap: any;
  stringToNewUTF8(str: string): number;
  UTF8ToString(ptr: number): string;
  _malloc(size: number): number;
  _free(ptr: number): void;
  HEAPU8: Uint8Array;
  HEAP32: Int32Array;
  wasmMemory?: WebAssembly.Memory;
  wasmModule?: WebAssembly.Module;
}

/**
 * Low-level FFI bindings to LEPUS/PrimJS's Emscripten module.
 * Native LEPUS API for direct PrimJS integration.
 *
 * @unstable The FFI interface is considered private and may change.
 */
export class LEPUSFFI {
  constructor(public module: LEPUSEmscriptenModule) {}
  /** Set at compile time. */
  readonly DEBUG = false


}
