// Cloudflare Worker specific utilities and examples
export interface WorkerContext {
  request: {
    url: string;
    method: string;
    headers: Record<string, string>;
  };
  env?: Record<string, any>;
  timestamp: string;
}

export interface WorkerResponse {
  status: number;
  headers: Record<string, string>;
  body: string | object;
  processing: {
    duration: number;
    timestamp: string;
    source: string;
  };
}

// Parse request information
export function parseWorkerRequest(url: string, method: string = 'GET'): {
  pathname: string;
  searchParams: Record<string, string>;
  segments: string[];
} {
  const urlObj = new URL(url);
  const searchParams: Record<string, string> = {};
  
  // Parse search params
  urlObj.searchParams.forEach((value, key) => {
    searchParams[key] = value;
  });

  return {
    pathname: urlObj.pathname,
    searchParams,
    segments: urlObj.pathname.split('/').filter(Boolean)
  };
}

// Generate worker-style responses
export function createWorkerResponse(
  data: any,
  status: number = 200,
  headers: Record<string, string> = {}
): WorkerResponse {
  const defaultHeaders = {
    'Content-Type': 'application/json',
    'Access-Control-Allow-Origin': '*',
    'Cache-Control': 'public, max-age=300'
  };

  return {
    status,
    headers: { ...defaultHeaders, ...headers },
    body: typeof data === 'string' ? data : JSON.stringify(data, null, 2),
    processing: {
      duration: Math.random() * 100 + 10, // Simulated processing time
      timestamp: new Date().toISOString(),
      source: 'Module Federation Worker Utils'
    }
  };
}

// Handle different HTTP methods
export function handleRequest(method: string, path: string, data?: any): WorkerResponse {
  const startTime = Date.now();
  
  switch (method.toUpperCase()) {
    case 'GET':
      return createWorkerResponse({
        message: `GET request to ${path}`,
        data: { path, timestamp: new Date().toISOString() }
      });
    
    case 'POST':
      return createWorkerResponse({
        message: `POST request to ${path}`,
        received: data,
        processed: true,
        id: Math.random().toString(36).substring(7)
      }, 201);
    
    case 'PUT':
      return createWorkerResponse({
        message: `PUT request to ${path}`,
        updated: data,
        success: true
      });
    
    case 'DELETE':
      return createWorkerResponse({
        message: `DELETE request to ${path}`,
        deleted: true,
        timestamp: new Date().toISOString()
      });
    
    default:
      return createWorkerResponse({
        error: `Method ${method} not supported`,
        supportedMethods: ['GET', 'POST', 'PUT', 'DELETE']
      }, 405);
  }
}

// Route handler simulation
export function routeHandler(pathname: string): WorkerResponse {
  const routes = {
    '/': createWorkerResponse({
      message: 'Welcome to Module Federation Worker',
      endpoints: ['/health', '/api/users', '/api/data', '/federation-demo'],
      timestamp: new Date().toISOString()
    }),
    
    '/health': createWorkerResponse({
      status: 'healthy',
      uptime: Math.floor(Math.random() * 86400), // Random uptime in seconds
      version: '1.0.0',
      federation: 'active'
    }),
    
    '/api/users': createWorkerResponse({
      users: [
        { id: 1, name: 'Alice', role: 'admin' },
        { id: 2, name: 'Bob', role: 'user' },
        { id: 3, name: 'Charlie', role: 'moderator' }
      ],
      total: 3,
      page: 1
    }),
    
    '/api/data': createWorkerResponse({
      metrics: {
        requests: Math.floor(Math.random() * 10000),
        errors: Math.floor(Math.random() * 100),
        uptime: '99.9%'
      },
      generated: new Date().toISOString()
    }),
    
    '/federation-demo': createWorkerResponse({
      demo: 'Module Federation on Cloudflare Workers',
      capabilities: [
        'Dynamic module loading',
        'Async/await support',
        'Promise handling',
        'KV storage integration',
        'QuickJS execution'
      ],
      example: 'This response was generated by a federated module!'
    })
  };

  return routes[pathname] || createWorkerResponse({
    error: 'Route not found',
    path: pathname,
    available: Object.keys(routes)
  }, 404);
}

// Simulate KV operations
export class MockKV {
  private store: Map<string, any> = new Map();

  async get(key: string): Promise<string | null> {
    return new Promise((resolve) => {
      setTimeout(() => {
        resolve(this.store.get(key) || null);
      }, Math.random() * 50 + 10); // 10-60ms delay
    });
  }

  async put(key: string, value: string): Promise<void> {
    return new Promise((resolve) => {
      setTimeout(() => {
        this.store.set(key, value);
        resolve();
      }, Math.random() * 30 + 5); // 5-35ms delay
    });
  }

  async delete(key: string): Promise<void> {
    return new Promise((resolve) => {
      setTimeout(() => {
        this.store.delete(key);
        resolve();
      }, Math.random() * 20 + 5); // 5-25ms delay
    });
  }

  async list(): Promise<string[]> {
    return new Promise((resolve) => {
      setTimeout(() => {
        resolve(Array.from(this.store.keys()));
      }, Math.random() * 40 + 10); // 10-50ms delay
    });
  }
}

// Demo function for worker capabilities
export async function demonstrateWorkerCapabilities(): Promise<any> {
  const kv = new MockKV();
  
  // KV operations
  await kv.put('user:1', JSON.stringify({ name: 'Alice', role: 'admin' }));
  await kv.put('config:app', JSON.stringify({ version: '1.0.0', debug: false }));
  
  const userData = await kv.get('user:1');
  const configData = await kv.get('config:app');
  const allKeys = await kv.list();

  // Request handling
  const getResponse = handleRequest('GET', '/api/users');
  const postResponse = handleRequest('POST', '/api/users', { name: 'David', role: 'user' });

  // Route handling
  const homeRoute = routeHandler('/');
  const healthRoute = routeHandler('/health');

  return {
    demo: 'worker-capabilities',
    timestamp: new Date().toISOString(),
    kv: {
      operations: ['put', 'get', 'list'],
      userData: userData ? JSON.parse(userData) : null,
      configData: configData ? JSON.parse(configData) : null,
      allKeys
    },
    requests: {
      get: getResponse,
      post: postResponse
    },
    routes: {
      home: homeRoute,
      health: healthRoute
    },
    summary: {
      kvOperations: 3,
      requestsHandled: 2,
      routesTested: 2,
      processing: 'successful'
    }
  };
}

// Format for CloudflareResponse
export function formatWorkerResult(result: any): {
  text: string;
  json: object;
  html: string;
} {
  return {
    text: JSON.stringify(result),
    json: result,
    html: `
      <div style="font-family: 'Courier New', monospace; padding: 20px; background: linear-gradient(135deg, #fd79a8 0%, #e84393 100%); color: white; border-radius: 8px;">
        <h2>🛠️ Worker Capabilities Demo</h2>
        <div style="background: rgba(255,255,255,0.1); padding: 15px; border-radius: 4px; margin: 10px 0;">
          <pre style="color: white; margin: 0; overflow-x: auto;">
${JSON.stringify(result, null, 2)}
          </pre>
        </div>
        <small>Generated by Module Federation Worker Utils</small>
      </div>
    `
  };
}